Add Enmap as custom database
Androz2091/discord-giveaways pull request #170
Opened 2021-01-04 14:10 UTC by GreepTheSheep

I had tried to do the same system as quick.db when I had Enmap, but I noticed that it was not the same system (the base gets corrupted when adding). So I modified and found this solution for those who use [Enmap](https://enmap.evie.dev/).

2021-01-04 15:22 UTC, Nico105 requested changes
Beautifying 😁 _So that every example is similar and commented_

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +        token: 'Your Discord Token'
```suggestion
        token: 'Your Discord Bot Token'
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +    // This function is called when the manager needs to get all the giveaway stored in the database.
```suggestion
    // This function is called when the manager needs to get all the giveaways stored in the database.
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +    async editGiveaway(messageID, giveawayData){
```suggestion
    // This function is called when a giveaway needs to be edited in the database.
    async editGiveaway(messageID, giveawayData) {
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +    console.log('I\'m ready !');
```suggestion
    console.log('I\'m ready!');
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +        exemptPermissions: [ 'MANAGE_MESSAGES', 'ADMINISTRATOR' ],
```suggestion
        exemptPermissions: ['MANAGE_MESSAGES', 'ADMINISTRATOR'],
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +
```suggestion
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +        return true;
```suggestion
        // Don't forget to return something!
        return true;
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +        return true;
```suggestion
        // Don't forget to return something!
        return true;
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +        return true;
```suggestion
        // Don't forget to return something!
        return true;
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +const giveawayDB = new Enmap({name: "giveaways"})
```suggestion
const giveawayDB = new Enmap({ name: 'giveaways' })
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +    async saveGiveaway(messageID, giveawayData){
```suggestion
    async saveGiveaway(messageID, giveawayData) {
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +    async deleteGiveaway(messageID){
```suggestion
    async deleteGiveaway(messageID) {
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +    async getAllGiveaways(){
```suggestion
    async getAllGiveaways() {
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +        return giveawayDB.fetchEverything().array();
```suggestion
        // Get all the giveaway in the database
        return giveawayDB.fetchEverything().array();
```

2021-01-04 15:22 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +        giveawayDB.set(messageID, giveawayData);
```suggestion
        // Add the new one
        giveawayDB.set(messageID, giveawayData);
```

2021-01-04 15:24 UTC, Nico105 commented
I would also suggest that you add a link to your example inside of the README.

2021-01-04 17:21 UTC, Snowflake107 requested changes
Use **[Enmap#ensure()](https://enmap.evie.dev/api#enmap-ensure-key-defaultvalue-path)**

2021-01-04 17:24 UTC, Nico105 commented
That's what I also thought in the first place but I mean the `giveawaDB` itself is a "collection" so we do not have to set it to [] right, and so why would we have to ensure then?
Or am I assuming wrong?

2021-01-04 17:29 UTC, Snowflake107 commented
why dont u make individual document instead of just one single array? You can manage stuff easily (as discord-giveaways is giving u full access to write custom manager)

2021-01-04 17:46 UTC, Nico105 reviewed
Like that? @Snowflake107

2021-01-04 17:46 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +const giveawayDB = new Enmap({ name: 'giveaways' })
```suggestion
const db = new Enmap({ name: 'giveaways' })
db.ensure('giveaways', [])
```

2021-01-04 17:46 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +        return giveawayDB.fetchEverything().array();
```suggestion
        return db.get('giveaways');
```

2021-01-04 17:46 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +        giveawayDB.set(messageID, giveawayData);
```suggestion
        db.push('giveaways', { giveawayData });
```

2021-01-04 17:46 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +        giveawayDB.set(messageID, giveawayData);
```suggestion
        // Gets all the current giveaways
        const giveaways = db.get('giveaways');
        // Remove the old giveaway from the current giveaways ID
        const newGiveawaysArray = giveaways.filter((giveaway) => giveaway.messageID !== messageID);
        // Push the new giveaway to the array
        newGiveawaysArray.push(giveawayData);
        // Save the updated array
        db.set('giveaways', newGiveawaysArray);
```

2021-01-04 17:46 UTC, Nico105 commented on examples/custom-databases/enmap.js
> +        giveawayDB.delete(messageID);
```suggestion
        // Remove the giveaway from the array
        const newGiveawaysArray = db.get('giveaways').filter((giveaway) => giveaway.messageID !== messageID);
        // Save the updated array
        db.set('giveaways', newGiveawaysArray);
        // Don't forget to return something!
        return true;
```

2021-01-05 06:45 UTC, GreepTheSheep commented
@Snowflake107 It's possible. But I want to base myself as for MySQL ie to create a new value when there is a new giveaway. Then I put it all together with `.array()`

2021-01-05 06:46 UTC, Snowflake107 commented
👍

2021-01-09 20:59 UTC, Androz2091 approved these changes
Thank you! 👍

2021-01-09 20:59 UTC, merged