✨Ability to pause/unpause giveaways
Androz2091/discord-giveaways pull request #269
Opened 2021-04-29 09:00 UTC by Lebyy

2021-05-17 10:30 UTC, Nico105 commented
I wonder, should content, unPauseAfter and embedColor also be a option for the pause function?
So the priority would be "function option>giveaway object>default"

2021-05-17 13:12 UTC, Lebyy commented
> I wonder, should there be an option in the pause function to overwrite the pauseOptions object?

Sure we can have it

2021-05-31 10:48 UTC, WiseDevHelper reviewed
Just a few minor suggestions.

2021-05-31 10:48 UTC, WiseDevHelper commented on README.md
> +### Un Pause a Giveaway
Better if just a single word.
```suggestion
### Unpause a Giveaway
```

2021-05-31 10:48 UTC, WiseDevHelper commented on README.md
> +            message.channel.send('Success! Giveaway un paused!');
Same as the previous suggestion.
```suggestion
            message.channel.send('Success! Giveaway unpaused!');
```

2021-05-31 10:48 UTC, WiseDevHelper commented on README.md
> +            message.channel.send('Encountered an error while un pausing giveaway with ID ' + messageID + 'Error: ' + err + '');
Same as the previous suggestion.
```suggestion
            message.channel.send('Encountered an error while unpausing giveaway with ID ' + messageID + '\nError: ' + err + '');
```

2021-05-31 16:08 UTC, Lebyy reviewed
Thanks, committed them👍

2021-06-04 15:27 UTC, Nico105 commented
Is the separate generateEmbed function really needed? Since I don't think you would allign the other messages in a different way just because the gaw is paused.

2021-06-07 10:33 UTC, Nico105 requested changes

2021-06-07 10:33 UTC, Nico105 commented on README.md
> +
I think it would be better if you move this directly under the "end" command example, since that are also cmds.

2021-06-07 10:33 UTC, Nico105 commented on examples/simple.js
> +    if(command === 'pause') {
```suggestion
    if (command === 'pause') {
```

2021-06-07 10:33 UTC, Nico105 commented on examples/simple.js
> +    if(command === 'unpause') {
```suggestion
    if (command === 'unpause') {
```

2021-06-07 10:33 UTC, Nico105 commented on src/Constants.js
> + * @property {string} [embedColor='#FFFF00'] The color of the embed when the giveaway is paused
```suggestion
 * @property {boolean} [isPaused=false] Whether the giveaway is paused
 * @property {string} [content='⚠️ **THIS GIVEAWAY IS PAUSED !** ⚠️'] The text of the embed when the giveaway is paused
 * @property {number} [unPauseAfter=null] The number of ms after which the giveaway will unpause
 * @property {string} [embedColor='#FFFF00'] The color of the embed when the giveaway is paused
```

2021-06-07 10:33 UTC, Nico105 commented on src/Constants.js
> + * @property {GiveawayPauseOptions} [pause] The pause system options
```suggestion
 * @property {GiveawayPauseOptions} [pauseOptions] The pause system options.
```

2021-06-07 10:33 UTC, Nico105 commented on src/Giveaway.js
> +        return this.options.pauseOptions
```suggestion
        return this.options.pauseOptions || defaultPauseOptions;
```
So you do not need to set it in the start function = saves db space.

2021-06-07 10:33 UTC, Nico105 commented on src/Giveaway.js
> +            if(this.pauseOptions.isPaused) return reject('Giveaway with ID ' + this.messageID + ' is already paused.');
```suggestion
            if (this.pauseOptions.isPaused) {
                return reject('Giveaway with ID ' + this.messageID + ' is already paused.');
            }
```

2021-06-07 10:33 UTC, Nico105 commented on src/Giveaway.js
> +            if(!this.pauseOptions.isPaused) return reject('Giveaway with ID ' + this.messageID + ' is not paused.');
```suggestion
            if (!this.pauseOptions.isPaused) {
                 return reject('Giveaway with ID ' + this.messageID + ' is not paused.');
             }
```

2021-06-07 10:33 UTC, Nico105 commented on src/Giveaway.js
> +            if(!this.pauseOptions.isPaused) return reject('Giveaway with ID ' + this.messageID + ' is not paused.');
I will maybe ask Androz somewhen if we can change to single line format cause I personally think it saves space and looks better when are able to do it in 1 line.
But for now I guess we should stick to the existing format.

2021-06-07 10:33 UTC, Nico105 commented on src/Manager.js
> +                pauseOptions: typeof options.pauseOptions === 'object' ? options.pauseOptions : defaultPauseOptions
```suggestion
                pauseOptions: typeof options.pauseOptions === 'object' ? options.pauseOptions : null
```
Saves db space = look at getter change

2021-06-07 10:33 UTC, Nico105 commented on src/Giveaway.js
> +    GiveawayPauseOptions
```suggestion
    GiveawayPauseOptions,
    defaultPauseOptions 
```

2021-06-07 10:33 UTC, Nico105 commented on src/Manager.js
> +            }
```suggestion
            if (giveaway.pauseOptions.isPaused) {
                if (giveaway.pauseOptions.unPauseAfter && !isNaN(giveaway.pauseOptions.unPauseAfter) && Date.now() >= giveaway.pauseOptions.unPauseAfter) return this.unpause(giveaway.messageID).catch(() => {});
                return;
            }
```

2021-06-07 10:33 UTC, Nico105 commented on typings/index.d.ts
> +        embedColor: string;
```suggestion
        embedColor: ColorResolvable;
```

2021-06-07 11:06 UTC, Lebyy reviewed
👍Alrighty

2021-06-19 14:58 UTC, Nico105 approved these changes
Seems finished to me. If anything is open lmk.

2021-06-23 07:42 UTC, Nico105 commented on README.md
> +⚠️ **Note**: the pause function overwrites/edits the [pauseOptions object property](https://github.com/Androz2091/discord-giveaways#pause-options) of the giveaway!
```suggestion
⚠️ **Note**: the pause function overwrites/edits the [pauseOptions object property](https://github.com/Androz2091/discord-giveaways#pause-options) of a giveaway!
```

2021-06-23 07:46 UTC, merged

2021-06-23 07:59 UTC, Lebyy commented
Thanks 😀