🐛 slash command examples
Androz2091/discord-giveaways pull request #359
Opened 2021-08-16 15:08 UTC by Nico105

_I haven't really used slash commands yet, so don't roast me if smth is totally wrong 😆_

I used `reply()` over `channe.send()` cause I think its a little more appropriate for slash commands.
But if someone thinks otherwise lmk.

Question: Is the `data` object fine to write out?
Since we could remove that and for registering just do `delete command.run`.
But that might confuse some people.
Lmk

2021-08-16 15:46 UTC, Dragonizedpizza requested changes
I think the snake case in the reroll command is unnecessary, considering that this is for the users to view, and Id looks weird. Also, the options' names must be lowercase (Discord API requires so), and I feel like the arrow function `run: async (interaction) => {` is unnecessary, when you could just do `async run(interaction) {`

2021-08-16 16:51 UTC, Nico105 commented
> I think the snake case in the reroll command is unnecessary, considering that this is for the users to view, and Id looks weird. Also, the options' names must be lowercase (Discord API requires so), and I feel like the arrow function `run: async (interaction) => {` is unnecessary, when you could just do `async run(interaction) {`

Now better?

2021-08-17 07:57 UTC, Dragonizedpizza commented
> > I think the snake case in the reroll command is unnecessary, considering that this is for the users to view, and Id looks weird. Also, the options' names must be lowercase (Discord API requires so), and I feel like the arrow function `run: async (interaction) => {` is unnecessary, when you could just do `async run(interaction) {`
> 
> Now better?

Yes, but why is the command run function async even though you're using .then?

2021-08-17 07:57 UTC, Dragonizedpizza commented
use async/await, its cleaner

2021-08-17 07:58 UTC, Dragonizedpizza commented
```js
await client.giveawaysManager.start(interaction.channel, { /** */ }),catch(() => { /** */ });
interaction.reply(yes)
```

2021-08-17 12:53 UTC, Nico105 commented
> ```js
> await client.giveawaysManager.start(interaction.channel, { /** */ }),catch(() => { /** */ });
> interaction.reply("yes")
> ```
> 
> also, I think the replying should be deferred incase for whatever reason it takes more than 3 seconds.

applied, tho i went with try catch cause returning would have been a little "fancy" otherwise

2021-08-28 12:29 UTC, Nico105 commented on src/Giveaway.js
> +                            .replace('{messageURL}', this.messageURL),
```suggestion
                            .replace('{messageURL}', this.messageURL)
```

2021-08-29 06:16 UTC, Androz2091 reviewed
Thank you for this very huge PR. I guess that the best way is to keep minimal examples (I will make a commit don't worry), but the best would be to create an example bot like the one in the examples folder of discord-player. I will make it too, based on this PR. Thank you very much again, sorry this close this.

2021-08-29 06:16 UTC, closed without merging